#!/bin/bash
# Regenerate present2/paper_data.js from the compiled paper PDF.
# Run after recompiling ../paper/paper.pdf.
set -e
cd "$(dirname "$0")"
B64=$(base64 -i ../paper/paper.pdf | tr -d '\n')
printf '// Auto-generated by update_paper.sh — do not edit by hand.\nconst PAPER_PDF_BASE64 = "%s";\n' "$B64" > paper_data.js
echo "paper_data.js updated ($(stat -f%z paper_data.js) bytes)"
